import { Types } from "mongoose";

const generateSongId = (): Types.ObjectId => {
  return new Types.ObjectId();
};

export const getSongIdByName = (title: string): Types.ObjectId => {
  return SONGS.find((song) => song.title === title)!._id;
};

export const SONGS = [
  {
    _id: generateSongId(),
    title: "Waiting For Love",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 3.5,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "Talk To Myself",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 3.55,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "Touch Me",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 3.06,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "Ten More Days",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 4.05,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "For A Better Day",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 3.26,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "Broken Arrows",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 3.52,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "True Believer",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 4.48,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "City Lights",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 6.28,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "Pure Grinding",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 2.51,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "Sunset Jesus",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 4.24,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "Can't Catch Me",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 3.59,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "Somewhere In Stockholm",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 3.22,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "Trouble",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 2.51,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "Gonna Love Ya",
    artist: "Avicii",
    album: "Waiting For Love",
    duration: 3.35,
    isFavorite: false,
  },
  {
    _id: generateSongId(),
    title: "God's Plan",
    artist: "Drake",
    album: "Scorpion",
    duration: 3.5,
    isFavorite: true,
    image: "gods_plan.jpg",
  },
  {
    _id: generateSongId(),
    title: "BREAK MY SOUL",
    artist: "Beyoncé",
    album: "Renaissance",
    duration: 4.38,
    isFavorite: true,
    image: "break_my_soul.jpg",
  },
  {
    _id: generateSongId(),
    title: "I’m Good(Blue)",
    artist: "David Guetta, Bebe Rexha",
    album: "I’m Good(Blue)",
    duration: 2.55,
    isFavorite: true,
    image: "im_good.jpg",
  },
  {
    _id: generateSongId(),
    title: "Die For You",
    artist: "The Weeknd",
    album: "Starboy",
    duration: 4.2,
    isFavorite: true,
    image: "die_for_you.jpg",
  },
  {
    _id: generateSongId(),
    title: "CLOUDS",
    artist: "NF",
    album: "CLOUDS(THE MIXTAPE)",
    duration: 4.03,
    isFavorite: true,
    image: "clouds.jpg",
  },
  {
    _id: generateSongId(),
    title: "Astronaut In The Ocean",
    artist: "Masked Wolf",
    album: "Astronaut In The Ocean",
    duration: 2.13,
    isFavorite: true,
    image: "astronaut_in_the_ocean.jpg",
  },
  {
    _id: generateSongId(),
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    duration: 3.2,
    isFavorite: true,
    image: "blinding_lights.jpg",
  },
];
