export class AlbumModel {
  public _id!: string; // generated by mongoDB
  public name!: string;
  public artist!: string;
  public image!: string;
  public artistImage!: string;
  public isFavorite!: boolean;
  public noTracks!: number;
  public yearProduced!: number;
  public duration!: number;
  public info!: string;
  public songs!: string[];

  constructor(model?: any) {
    Object.assign(this, model);
  }
}

export class AlbumDummyModel {
  public name!: string;
  public artist!: string;
  public image!: string;
  public isFavorite!: boolean;
  public noTracks!: number;

  constructor(model?: any) {
    Object.assign(this, model);
  }
}
